[project]
name = "stat386-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matthew", email = "davismatthewrocks@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
stat386-site = "stat386_site:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
